/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2NullableGatewayConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2NullableGatewayConfig{}

// ManaV2NullableGatewayConfig struct for ManaV2NullableGatewayConfig
type ManaV2NullableGatewayConfig struct {
	Address *string `json:"address,omitempty"`
}

// NewManaV2NullableGatewayConfig instantiates a new ManaV2NullableGatewayConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2NullableGatewayConfig() *ManaV2NullableGatewayConfig {
	this := ManaV2NullableGatewayConfig{}
	return &this
}

// NewManaV2NullableGatewayConfigWithDefaults instantiates a new ManaV2NullableGatewayConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2NullableGatewayConfigWithDefaults() *ManaV2NullableGatewayConfig {
	this := ManaV2NullableGatewayConfig{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ManaV2NullableGatewayConfig) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2NullableGatewayConfig) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ManaV2NullableGatewayConfig) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ManaV2NullableGatewayConfig) SetAddress(v string) {
	o.Address = &v
}

func (o ManaV2NullableGatewayConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2NullableGatewayConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

type NullableManaV2NullableGatewayConfig struct {
	value *ManaV2NullableGatewayConfig
	isSet bool
}

func (v NullableManaV2NullableGatewayConfig) Get() *ManaV2NullableGatewayConfig {
	return v.value
}

func (v *NullableManaV2NullableGatewayConfig) Set(val *ManaV2NullableGatewayConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2NullableGatewayConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2NullableGatewayConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2NullableGatewayConfig(val *ManaV2NullableGatewayConfig) *NullableManaV2NullableGatewayConfig {
	return &NullableManaV2NullableGatewayConfig{value: val, isSet: true}
}

func (v NullableManaV2NullableGatewayConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2NullableGatewayConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


