/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManaV2MaCsecConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2MaCsecConfiguration{}

// ManaV2MaCsecConfiguration struct for ManaV2MaCsecConfiguration
type ManaV2MaCsecConfiguration struct {
	// Whether MACsec is enabled or disabled (required)
	Enabled bool `json:"enabled"`
	// The encryption enforcement mode (required)
	EncryptionEnforcementMode string `json:"encryptionEnforcementMode"`
	GlobalSakConfiguration ManaV2NullableSakConfiguration `json:"globalSakConfiguration"`
	// The priority of the key server. Lower number means higher priority.
	KeyServerPriority *int64 `json:"keyServerPriority,omitempty"`
	PskConfigurations []ManaV2PskConfiguration `json:"pskConfigurations,omitempty"`
	PskConfigurationsByNickname map[string]ManaV2NullablePskConfiguration `json:"pskConfigurationsByNickname"`
	SakConfigurations []ManaV2SakConfiguration `json:"sakConfigurations,omitempty"`
	SakConfigurationsByLagMemberInterfaceId map[string]ManaV2NullableSakConfiguration `json:"sakConfigurationsByLagMemberInterfaceId"`
	// Whether to allow individual SAK configurations for each lag member
	SplitSakConfigByLagMember *bool `json:"splitSakConfigByLagMember,omitempty"`
	// Whether transparent VLAN is enabled or disabled
	TransparentVlan *bool `json:"transparentVlan,omitempty"`
}

type _ManaV2MaCsecConfiguration ManaV2MaCsecConfiguration

// NewManaV2MaCsecConfiguration instantiates a new ManaV2MaCsecConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2MaCsecConfiguration(enabled bool, encryptionEnforcementMode string, globalSakConfiguration ManaV2NullableSakConfiguration, pskConfigurationsByNickname map[string]ManaV2NullablePskConfiguration, sakConfigurationsByLagMemberInterfaceId map[string]ManaV2NullableSakConfiguration) *ManaV2MaCsecConfiguration {
	this := ManaV2MaCsecConfiguration{}
	this.Enabled = enabled
	this.EncryptionEnforcementMode = encryptionEnforcementMode
	this.GlobalSakConfiguration = globalSakConfiguration
	this.PskConfigurationsByNickname = pskConfigurationsByNickname
	this.SakConfigurationsByLagMemberInterfaceId = sakConfigurationsByLagMemberInterfaceId
	return &this
}

// NewManaV2MaCsecConfigurationWithDefaults instantiates a new ManaV2MaCsecConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2MaCsecConfigurationWithDefaults() *ManaV2MaCsecConfiguration {
	this := ManaV2MaCsecConfiguration{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *ManaV2MaCsecConfiguration) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ManaV2MaCsecConfiguration) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ManaV2MaCsecConfiguration) SetEnabled(v bool) {
	o.Enabled = v
}

// GetEncryptionEnforcementMode returns the EncryptionEnforcementMode field value
func (o *ManaV2MaCsecConfiguration) GetEncryptionEnforcementMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EncryptionEnforcementMode
}

// GetEncryptionEnforcementModeOk returns a tuple with the EncryptionEnforcementMode field value
// and a boolean to check if the value has been set.
func (o *ManaV2MaCsecConfiguration) GetEncryptionEnforcementModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EncryptionEnforcementMode, true
}

// SetEncryptionEnforcementMode sets field value
func (o *ManaV2MaCsecConfiguration) SetEncryptionEnforcementMode(v string) {
	o.EncryptionEnforcementMode = v
}

// GetGlobalSakConfiguration returns the GlobalSakConfiguration field value
func (o *ManaV2MaCsecConfiguration) GetGlobalSakConfiguration() ManaV2NullableSakConfiguration {
	if o == nil {
		var ret ManaV2NullableSakConfiguration
		return ret
	}

	return o.GlobalSakConfiguration
}

// GetGlobalSakConfigurationOk returns a tuple with the GlobalSakConfiguration field value
// and a boolean to check if the value has been set.
func (o *ManaV2MaCsecConfiguration) GetGlobalSakConfigurationOk() (*ManaV2NullableSakConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GlobalSakConfiguration, true
}

// SetGlobalSakConfiguration sets field value
func (o *ManaV2MaCsecConfiguration) SetGlobalSakConfiguration(v ManaV2NullableSakConfiguration) {
	o.GlobalSakConfiguration = v
}

// GetKeyServerPriority returns the KeyServerPriority field value if set, zero value otherwise.
func (o *ManaV2MaCsecConfiguration) GetKeyServerPriority() int64 {
	if o == nil || IsNil(o.KeyServerPriority) {
		var ret int64
		return ret
	}
	return *o.KeyServerPriority
}

// GetKeyServerPriorityOk returns a tuple with the KeyServerPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2MaCsecConfiguration) GetKeyServerPriorityOk() (*int64, bool) {
	if o == nil || IsNil(o.KeyServerPriority) {
		return nil, false
	}
	return o.KeyServerPriority, true
}

// HasKeyServerPriority returns a boolean if a field has been set.
func (o *ManaV2MaCsecConfiguration) HasKeyServerPriority() bool {
	if o != nil && !IsNil(o.KeyServerPriority) {
		return true
	}

	return false
}

// SetKeyServerPriority gets a reference to the given int64 and assigns it to the KeyServerPriority field.
func (o *ManaV2MaCsecConfiguration) SetKeyServerPriority(v int64) {
	o.KeyServerPriority = &v
}

// GetPskConfigurations returns the PskConfigurations field value if set, zero value otherwise.
func (o *ManaV2MaCsecConfiguration) GetPskConfigurations() []ManaV2PskConfiguration {
	if o == nil || IsNil(o.PskConfigurations) {
		var ret []ManaV2PskConfiguration
		return ret
	}
	return o.PskConfigurations
}

// GetPskConfigurationsOk returns a tuple with the PskConfigurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2MaCsecConfiguration) GetPskConfigurationsOk() ([]ManaV2PskConfiguration, bool) {
	if o == nil || IsNil(o.PskConfigurations) {
		return nil, false
	}
	return o.PskConfigurations, true
}

// HasPskConfigurations returns a boolean if a field has been set.
func (o *ManaV2MaCsecConfiguration) HasPskConfigurations() bool {
	if o != nil && !IsNil(o.PskConfigurations) {
		return true
	}

	return false
}

// SetPskConfigurations gets a reference to the given []ManaV2PskConfiguration and assigns it to the PskConfigurations field.
func (o *ManaV2MaCsecConfiguration) SetPskConfigurations(v []ManaV2PskConfiguration) {
	o.PskConfigurations = v
}

// GetPskConfigurationsByNickname returns the PskConfigurationsByNickname field value
func (o *ManaV2MaCsecConfiguration) GetPskConfigurationsByNickname() map[string]ManaV2NullablePskConfiguration {
	if o == nil {
		var ret map[string]ManaV2NullablePskConfiguration
		return ret
	}

	return o.PskConfigurationsByNickname
}

// GetPskConfigurationsByNicknameOk returns a tuple with the PskConfigurationsByNickname field value
// and a boolean to check if the value has been set.
func (o *ManaV2MaCsecConfiguration) GetPskConfigurationsByNicknameOk() (*map[string]ManaV2NullablePskConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PskConfigurationsByNickname, true
}

// SetPskConfigurationsByNickname sets field value
func (o *ManaV2MaCsecConfiguration) SetPskConfigurationsByNickname(v map[string]ManaV2NullablePskConfiguration) {
	o.PskConfigurationsByNickname = v
}

// GetSakConfigurations returns the SakConfigurations field value if set, zero value otherwise.
func (o *ManaV2MaCsecConfiguration) GetSakConfigurations() []ManaV2SakConfiguration {
	if o == nil || IsNil(o.SakConfigurations) {
		var ret []ManaV2SakConfiguration
		return ret
	}
	return o.SakConfigurations
}

// GetSakConfigurationsOk returns a tuple with the SakConfigurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2MaCsecConfiguration) GetSakConfigurationsOk() ([]ManaV2SakConfiguration, bool) {
	if o == nil || IsNil(o.SakConfigurations) {
		return nil, false
	}
	return o.SakConfigurations, true
}

// HasSakConfigurations returns a boolean if a field has been set.
func (o *ManaV2MaCsecConfiguration) HasSakConfigurations() bool {
	if o != nil && !IsNil(o.SakConfigurations) {
		return true
	}

	return false
}

// SetSakConfigurations gets a reference to the given []ManaV2SakConfiguration and assigns it to the SakConfigurations field.
func (o *ManaV2MaCsecConfiguration) SetSakConfigurations(v []ManaV2SakConfiguration) {
	o.SakConfigurations = v
}

// GetSakConfigurationsByLagMemberInterfaceId returns the SakConfigurationsByLagMemberInterfaceId field value
func (o *ManaV2MaCsecConfiguration) GetSakConfigurationsByLagMemberInterfaceId() map[string]ManaV2NullableSakConfiguration {
	if o == nil {
		var ret map[string]ManaV2NullableSakConfiguration
		return ret
	}

	return o.SakConfigurationsByLagMemberInterfaceId
}

// GetSakConfigurationsByLagMemberInterfaceIdOk returns a tuple with the SakConfigurationsByLagMemberInterfaceId field value
// and a boolean to check if the value has been set.
func (o *ManaV2MaCsecConfiguration) GetSakConfigurationsByLagMemberInterfaceIdOk() (*map[string]ManaV2NullableSakConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SakConfigurationsByLagMemberInterfaceId, true
}

// SetSakConfigurationsByLagMemberInterfaceId sets field value
func (o *ManaV2MaCsecConfiguration) SetSakConfigurationsByLagMemberInterfaceId(v map[string]ManaV2NullableSakConfiguration) {
	o.SakConfigurationsByLagMemberInterfaceId = v
}

// GetSplitSakConfigByLagMember returns the SplitSakConfigByLagMember field value if set, zero value otherwise.
func (o *ManaV2MaCsecConfiguration) GetSplitSakConfigByLagMember() bool {
	if o == nil || IsNil(o.SplitSakConfigByLagMember) {
		var ret bool
		return ret
	}
	return *o.SplitSakConfigByLagMember
}

// GetSplitSakConfigByLagMemberOk returns a tuple with the SplitSakConfigByLagMember field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2MaCsecConfiguration) GetSplitSakConfigByLagMemberOk() (*bool, bool) {
	if o == nil || IsNil(o.SplitSakConfigByLagMember) {
		return nil, false
	}
	return o.SplitSakConfigByLagMember, true
}

// HasSplitSakConfigByLagMember returns a boolean if a field has been set.
func (o *ManaV2MaCsecConfiguration) HasSplitSakConfigByLagMember() bool {
	if o != nil && !IsNil(o.SplitSakConfigByLagMember) {
		return true
	}

	return false
}

// SetSplitSakConfigByLagMember gets a reference to the given bool and assigns it to the SplitSakConfigByLagMember field.
func (o *ManaV2MaCsecConfiguration) SetSplitSakConfigByLagMember(v bool) {
	o.SplitSakConfigByLagMember = &v
}

// GetTransparentVlan returns the TransparentVlan field value if set, zero value otherwise.
func (o *ManaV2MaCsecConfiguration) GetTransparentVlan() bool {
	if o == nil || IsNil(o.TransparentVlan) {
		var ret bool
		return ret
	}
	return *o.TransparentVlan
}

// GetTransparentVlanOk returns a tuple with the TransparentVlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2MaCsecConfiguration) GetTransparentVlanOk() (*bool, bool) {
	if o == nil || IsNil(o.TransparentVlan) {
		return nil, false
	}
	return o.TransparentVlan, true
}

// HasTransparentVlan returns a boolean if a field has been set.
func (o *ManaV2MaCsecConfiguration) HasTransparentVlan() bool {
	if o != nil && !IsNil(o.TransparentVlan) {
		return true
	}

	return false
}

// SetTransparentVlan gets a reference to the given bool and assigns it to the TransparentVlan field.
func (o *ManaV2MaCsecConfiguration) SetTransparentVlan(v bool) {
	o.TransparentVlan = &v
}

func (o ManaV2MaCsecConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2MaCsecConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["encryptionEnforcementMode"] = o.EncryptionEnforcementMode
	toSerialize["globalSakConfiguration"] = o.GlobalSakConfiguration
	if !IsNil(o.KeyServerPriority) {
		toSerialize["keyServerPriority"] = o.KeyServerPriority
	}
	if !IsNil(o.PskConfigurations) {
		toSerialize["pskConfigurations"] = o.PskConfigurations
	}
	toSerialize["pskConfigurationsByNickname"] = o.PskConfigurationsByNickname
	if !IsNil(o.SakConfigurations) {
		toSerialize["sakConfigurations"] = o.SakConfigurations
	}
	toSerialize["sakConfigurationsByLagMemberInterfaceId"] = o.SakConfigurationsByLagMemberInterfaceId
	if !IsNil(o.SplitSakConfigByLagMember) {
		toSerialize["splitSakConfigByLagMember"] = o.SplitSakConfigByLagMember
	}
	if !IsNil(o.TransparentVlan) {
		toSerialize["transparentVlan"] = o.TransparentVlan
	}
	return toSerialize, nil
}

func (o *ManaV2MaCsecConfiguration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"encryptionEnforcementMode",
		"globalSakConfiguration",
		"pskConfigurationsByNickname",
		"sakConfigurationsByLagMemberInterfaceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManaV2MaCsecConfiguration := _ManaV2MaCsecConfiguration{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManaV2MaCsecConfiguration)

	if err != nil {
		return err
	}

	*o = ManaV2MaCsecConfiguration(varManaV2MaCsecConfiguration)

	return err
}

type NullableManaV2MaCsecConfiguration struct {
	value *ManaV2MaCsecConfiguration
	isSet bool
}

func (v NullableManaV2MaCsecConfiguration) Get() *ManaV2MaCsecConfiguration {
	return v.value
}

func (v *NullableManaV2MaCsecConfiguration) Set(val *ManaV2MaCsecConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2MaCsecConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2MaCsecConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2MaCsecConfiguration(val *ManaV2MaCsecConfiguration) *NullableManaV2MaCsecConfiguration {
	return &NullableManaV2MaCsecConfiguration{value: val, isSet: true}
}

func (v NullableManaV2MaCsecConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2MaCsecConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


