/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1UsersPasswordsExpirePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1UsersPasswordsExpirePostRequest{}

// V1UsersPasswordsExpirePostRequest struct for V1UsersPasswordsExpirePostRequest
type V1UsersPasswordsExpirePostRequest struct {
	UserIds []string `json:"userIds"`
}

type _V1UsersPasswordsExpirePostRequest V1UsersPasswordsExpirePostRequest

// NewV1UsersPasswordsExpirePostRequest instantiates a new V1UsersPasswordsExpirePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1UsersPasswordsExpirePostRequest(userIds []string) *V1UsersPasswordsExpirePostRequest {
	this := V1UsersPasswordsExpirePostRequest{}
	this.UserIds = userIds
	return &this
}

// NewV1UsersPasswordsExpirePostRequestWithDefaults instantiates a new V1UsersPasswordsExpirePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1UsersPasswordsExpirePostRequestWithDefaults() *V1UsersPasswordsExpirePostRequest {
	this := V1UsersPasswordsExpirePostRequest{}
	return &this
}

// GetUserIds returns the UserIds field value
func (o *V1UsersPasswordsExpirePostRequest) GetUserIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UserIds
}

// GetUserIdsOk returns a tuple with the UserIds field value
// and a boolean to check if the value has been set.
func (o *V1UsersPasswordsExpirePostRequest) GetUserIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserIds, true
}

// SetUserIds sets field value
func (o *V1UsersPasswordsExpirePostRequest) SetUserIds(v []string) {
	o.UserIds = v
}

func (o V1UsersPasswordsExpirePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1UsersPasswordsExpirePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userIds"] = o.UserIds
	return toSerialize, nil
}

func (o *V1UsersPasswordsExpirePostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1UsersPasswordsExpirePostRequest := _V1UsersPasswordsExpirePostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1UsersPasswordsExpirePostRequest)

	if err != nil {
		return err
	}

	*o = V1UsersPasswordsExpirePostRequest(varV1UsersPasswordsExpirePostRequest)

	return err
}

type NullableV1UsersPasswordsExpirePostRequest struct {
	value *V1UsersPasswordsExpirePostRequest
	isSet bool
}

func (v NullableV1UsersPasswordsExpirePostRequest) Get() *V1UsersPasswordsExpirePostRequest {
	return v.value
}

func (v *NullableV1UsersPasswordsExpirePostRequest) Set(val *V1UsersPasswordsExpirePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1UsersPasswordsExpirePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1UsersPasswordsExpirePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1UsersPasswordsExpirePostRequest(val *V1UsersPasswordsExpirePostRequest) *NullableV1UsersPasswordsExpirePostRequest {
	return &NullableV1UsersPasswordsExpirePostRequest{value: val, isSet: true}
}

func (v NullableV1UsersPasswordsExpirePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1UsersPasswordsExpirePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


