/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse{}

// V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse struct for V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse
type V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse struct {
	ConsumerActiviyId *string `json:"consumerActiviyId,omitempty"`
}

// NewV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse instantiates a new V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse() *V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse {
	this := V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse{}
	return &this
}

// NewV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponseWithDefaults instantiates a new V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponseWithDefaults() *V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse {
	this := V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse{}
	return &this
}

// GetConsumerActiviyId returns the ConsumerActiviyId field value if set, zero value otherwise.
func (o *V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) GetConsumerActiviyId() string {
	if o == nil || IsNil(o.ConsumerActiviyId) {
		var ret string
		return ret
	}
	return *o.ConsumerActiviyId
}

// GetConsumerActiviyIdOk returns a tuple with the ConsumerActiviyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) GetConsumerActiviyIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConsumerActiviyId) {
		return nil, false
	}
	return o.ConsumerActiviyId, true
}

// HasConsumerActiviyId returns a boolean if a field has been set.
func (o *V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) HasConsumerActiviyId() bool {
	if o != nil && !IsNil(o.ConsumerActiviyId) {
		return true
	}

	return false
}

// SetConsumerActiviyId gets a reference to the given string and assigns it to the ConsumerActiviyId field.
func (o *V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) SetConsumerActiviyId(v string) {
	o.ConsumerActiviyId = &v
}

func (o V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConsumerActiviyId) {
		toSerialize["consumerActiviyId"] = o.ConsumerActiviyId
	}
	return toSerialize, nil
}

type NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse struct {
	value *V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse
	isSet bool
}

func (v NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) Get() *V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse {
	return v.value
}

func (v *NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) Set(val *V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse(val *V1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) *NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse {
	return &NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


