/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2PskConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2PskConfiguration{}

// ManaV2PskConfiguration struct for ManaV2PskConfiguration
type ManaV2PskConfiguration struct {
	// The Connection Authentication Key (CAK)
	Cak *string `json:"cak,omitempty"`
	// The cryptographic algorithm for the CAK (required)
	CakCryptographicAlgorithm *string `json:"cakCryptographicAlgorithm,omitempty"`
	// The Connection Key Name (CKN) (required)
	Ckn *string `json:"ckn,omitempty"`
	// The nickname of the PSK (required)
	Nickname *string `json:"nickname,omitempty"`
	StartTime *GoogleProtobufTimestamp `json:"startTime,omitempty"`
}

// NewManaV2PskConfiguration instantiates a new ManaV2PskConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2PskConfiguration() *ManaV2PskConfiguration {
	this := ManaV2PskConfiguration{}
	return &this
}

// NewManaV2PskConfigurationWithDefaults instantiates a new ManaV2PskConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2PskConfigurationWithDefaults() *ManaV2PskConfiguration {
	this := ManaV2PskConfiguration{}
	return &this
}

// GetCak returns the Cak field value if set, zero value otherwise.
func (o *ManaV2PskConfiguration) GetCak() string {
	if o == nil || IsNil(o.Cak) {
		var ret string
		return ret
	}
	return *o.Cak
}

// GetCakOk returns a tuple with the Cak field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PskConfiguration) GetCakOk() (*string, bool) {
	if o == nil || IsNil(o.Cak) {
		return nil, false
	}
	return o.Cak, true
}

// HasCak returns a boolean if a field has been set.
func (o *ManaV2PskConfiguration) HasCak() bool {
	if o != nil && !IsNil(o.Cak) {
		return true
	}

	return false
}

// SetCak gets a reference to the given string and assigns it to the Cak field.
func (o *ManaV2PskConfiguration) SetCak(v string) {
	o.Cak = &v
}

// GetCakCryptographicAlgorithm returns the CakCryptographicAlgorithm field value if set, zero value otherwise.
func (o *ManaV2PskConfiguration) GetCakCryptographicAlgorithm() string {
	if o == nil || IsNil(o.CakCryptographicAlgorithm) {
		var ret string
		return ret
	}
	return *o.CakCryptographicAlgorithm
}

// GetCakCryptographicAlgorithmOk returns a tuple with the CakCryptographicAlgorithm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PskConfiguration) GetCakCryptographicAlgorithmOk() (*string, bool) {
	if o == nil || IsNil(o.CakCryptographicAlgorithm) {
		return nil, false
	}
	return o.CakCryptographicAlgorithm, true
}

// HasCakCryptographicAlgorithm returns a boolean if a field has been set.
func (o *ManaV2PskConfiguration) HasCakCryptographicAlgorithm() bool {
	if o != nil && !IsNil(o.CakCryptographicAlgorithm) {
		return true
	}

	return false
}

// SetCakCryptographicAlgorithm gets a reference to the given string and assigns it to the CakCryptographicAlgorithm field.
func (o *ManaV2PskConfiguration) SetCakCryptographicAlgorithm(v string) {
	o.CakCryptographicAlgorithm = &v
}

// GetCkn returns the Ckn field value if set, zero value otherwise.
func (o *ManaV2PskConfiguration) GetCkn() string {
	if o == nil || IsNil(o.Ckn) {
		var ret string
		return ret
	}
	return *o.Ckn
}

// GetCknOk returns a tuple with the Ckn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PskConfiguration) GetCknOk() (*string, bool) {
	if o == nil || IsNil(o.Ckn) {
		return nil, false
	}
	return o.Ckn, true
}

// HasCkn returns a boolean if a field has been set.
func (o *ManaV2PskConfiguration) HasCkn() bool {
	if o != nil && !IsNil(o.Ckn) {
		return true
	}

	return false
}

// SetCkn gets a reference to the given string and assigns it to the Ckn field.
func (o *ManaV2PskConfiguration) SetCkn(v string) {
	o.Ckn = &v
}

// GetNickname returns the Nickname field value if set, zero value otherwise.
func (o *ManaV2PskConfiguration) GetNickname() string {
	if o == nil || IsNil(o.Nickname) {
		var ret string
		return ret
	}
	return *o.Nickname
}

// GetNicknameOk returns a tuple with the Nickname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PskConfiguration) GetNicknameOk() (*string, bool) {
	if o == nil || IsNil(o.Nickname) {
		return nil, false
	}
	return o.Nickname, true
}

// HasNickname returns a boolean if a field has been set.
func (o *ManaV2PskConfiguration) HasNickname() bool {
	if o != nil && !IsNil(o.Nickname) {
		return true
	}

	return false
}

// SetNickname gets a reference to the given string and assigns it to the Nickname field.
func (o *ManaV2PskConfiguration) SetNickname(v string) {
	o.Nickname = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *ManaV2PskConfiguration) GetStartTime() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.StartTime) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PskConfiguration) GetStartTimeOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *ManaV2PskConfiguration) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given GoogleProtobufTimestamp and assigns it to the StartTime field.
func (o *ManaV2PskConfiguration) SetStartTime(v GoogleProtobufTimestamp) {
	o.StartTime = &v
}

func (o ManaV2PskConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2PskConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cak) {
		toSerialize["cak"] = o.Cak
	}
	if !IsNil(o.CakCryptographicAlgorithm) {
		toSerialize["cakCryptographicAlgorithm"] = o.CakCryptographicAlgorithm
	}
	if !IsNil(o.Ckn) {
		toSerialize["ckn"] = o.Ckn
	}
	if !IsNil(o.Nickname) {
		toSerialize["nickname"] = o.Nickname
	}
	if !IsNil(o.StartTime) {
		toSerialize["startTime"] = o.StartTime
	}
	return toSerialize, nil
}

type NullableManaV2PskConfiguration struct {
	value *ManaV2PskConfiguration
	isSet bool
}

func (v NullableManaV2PskConfiguration) Get() *ManaV2PskConfiguration {
	return v.value
}

func (v *NullableManaV2PskConfiguration) Set(val *ManaV2PskConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2PskConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2PskConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2PskConfiguration(val *ManaV2PskConfiguration) *NullableManaV2PskConfiguration {
	return &NullableManaV2PskConfiguration{value: val, isSet: true}
}

func (v NullableManaV2PskConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2PskConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


