/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssuranceDnsProxyEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssuranceDnsProxyEntry{}

// AssuranceDnsProxyEntry struct for AssuranceDnsProxyEntry
type AssuranceDnsProxyEntry struct {
	// dns proxy table entry id (required)
	DnsproxyEntryId string `json:"dnsproxyEntryId"`
	IpList []string `json:"ipList"`
	// name of the entry  (required)
	Name string `json:"name"`
	// user defined name of the record (required)
	NameText string `json:"nameText"`
	PortList []string `json:"portList"`
	// protocol to exclude (required)
	Protocol string `json:"protocol"`
}

type _AssuranceDnsProxyEntry AssuranceDnsProxyEntry

// NewAssuranceDnsProxyEntry instantiates a new AssuranceDnsProxyEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssuranceDnsProxyEntry(dnsproxyEntryId string, ipList []string, name string, nameText string, portList []string, protocol string) *AssuranceDnsProxyEntry {
	this := AssuranceDnsProxyEntry{}
	this.DnsproxyEntryId = dnsproxyEntryId
	this.IpList = ipList
	this.Name = name
	this.NameText = nameText
	this.PortList = portList
	this.Protocol = protocol
	return &this
}

// NewAssuranceDnsProxyEntryWithDefaults instantiates a new AssuranceDnsProxyEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssuranceDnsProxyEntryWithDefaults() *AssuranceDnsProxyEntry {
	this := AssuranceDnsProxyEntry{}
	return &this
}

// GetDnsproxyEntryId returns the DnsproxyEntryId field value
func (o *AssuranceDnsProxyEntry) GetDnsproxyEntryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DnsproxyEntryId
}

// GetDnsproxyEntryIdOk returns a tuple with the DnsproxyEntryId field value
// and a boolean to check if the value has been set.
func (o *AssuranceDnsProxyEntry) GetDnsproxyEntryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DnsproxyEntryId, true
}

// SetDnsproxyEntryId sets field value
func (o *AssuranceDnsProxyEntry) SetDnsproxyEntryId(v string) {
	o.DnsproxyEntryId = v
}

// GetIpList returns the IpList field value
func (o *AssuranceDnsProxyEntry) GetIpList() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.IpList
}

// GetIpListOk returns a tuple with the IpList field value
// and a boolean to check if the value has been set.
func (o *AssuranceDnsProxyEntry) GetIpListOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpList, true
}

// SetIpList sets field value
func (o *AssuranceDnsProxyEntry) SetIpList(v []string) {
	o.IpList = v
}

// GetName returns the Name field value
func (o *AssuranceDnsProxyEntry) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AssuranceDnsProxyEntry) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AssuranceDnsProxyEntry) SetName(v string) {
	o.Name = v
}

// GetNameText returns the NameText field value
func (o *AssuranceDnsProxyEntry) GetNameText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NameText
}

// GetNameTextOk returns a tuple with the NameText field value
// and a boolean to check if the value has been set.
func (o *AssuranceDnsProxyEntry) GetNameTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NameText, true
}

// SetNameText sets field value
func (o *AssuranceDnsProxyEntry) SetNameText(v string) {
	o.NameText = v
}

// GetPortList returns the PortList field value
func (o *AssuranceDnsProxyEntry) GetPortList() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PortList
}

// GetPortListOk returns a tuple with the PortList field value
// and a boolean to check if the value has been set.
func (o *AssuranceDnsProxyEntry) GetPortListOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PortList, true
}

// SetPortList sets field value
func (o *AssuranceDnsProxyEntry) SetPortList(v []string) {
	o.PortList = v
}

// GetProtocol returns the Protocol field value
func (o *AssuranceDnsProxyEntry) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *AssuranceDnsProxyEntry) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *AssuranceDnsProxyEntry) SetProtocol(v string) {
	o.Protocol = v
}

func (o AssuranceDnsProxyEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssuranceDnsProxyEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dnsproxyEntryId"] = o.DnsproxyEntryId
	toSerialize["ipList"] = o.IpList
	toSerialize["name"] = o.Name
	toSerialize["nameText"] = o.NameText
	toSerialize["portList"] = o.PortList
	toSerialize["protocol"] = o.Protocol
	return toSerialize, nil
}

func (o *AssuranceDnsProxyEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dnsproxyEntryId",
		"ipList",
		"name",
		"nameText",
		"portList",
		"protocol",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssuranceDnsProxyEntry := _AssuranceDnsProxyEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssuranceDnsProxyEntry)

	if err != nil {
		return err
	}

	*o = AssuranceDnsProxyEntry(varAssuranceDnsProxyEntry)

	return err
}

type NullableAssuranceDnsProxyEntry struct {
	value *AssuranceDnsProxyEntry
	isSet bool
}

func (v NullableAssuranceDnsProxyEntry) Get() *AssuranceDnsProxyEntry {
	return v.value
}

func (v *NullableAssuranceDnsProxyEntry) Set(val *AssuranceDnsProxyEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableAssuranceDnsProxyEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableAssuranceDnsProxyEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssuranceDnsProxyEntry(val *AssuranceDnsProxyEntry) *NullableAssuranceDnsProxyEntry {
	return &NullableAssuranceDnsProxyEntry{value: val, isSet: true}
}

func (v NullableAssuranceDnsProxyEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssuranceDnsProxyEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


