/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest{}

// V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest struct for V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest
type V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest struct {
	ServicePrefixes []ManaV2B2bNat `json:"servicePrefixes"`
}

type _V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest

// NewV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest instantiates a new V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest(servicePrefixes []ManaV2B2bNat) *V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest {
	this := V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest{}
	this.ServicePrefixes = servicePrefixes
	return &this
}

// NewV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequestWithDefaults instantiates a new V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequestWithDefaults() *V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest {
	this := V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest{}
	return &this
}

// GetServicePrefixes returns the ServicePrefixes field value
func (o *V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) GetServicePrefixes() []ManaV2B2bNat {
	if o == nil {
		var ret []ManaV2B2bNat
		return ret
	}

	return o.ServicePrefixes
}

// GetServicePrefixesOk returns a tuple with the ServicePrefixes field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) GetServicePrefixesOk() ([]ManaV2B2bNat, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServicePrefixes, true
}

// SetServicePrefixes sets field value
func (o *V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) SetServicePrefixes(v []ManaV2B2bNat) {
	o.ServicePrefixes = v
}

func (o V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["servicePrefixes"] = o.ServicePrefixes
	return toSerialize, nil
}

func (o *V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"servicePrefixes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest := _V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest)

	if err != nil {
		return err
	}

	*o = V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest(varV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest)

	return err
}

type NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest struct {
	value *V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest
	isSet bool
}

func (v NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) Get() *V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest {
	return v.value
}

func (v *NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) Set(val *V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest(val *V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) *NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest {
	return &NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


