/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2InterfaceMaCsec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2InterfaceMaCsec{}

// ManaV2InterfaceMaCsec struct for ManaV2InterfaceMaCsec
type ManaV2InterfaceMaCsec struct {
	Enabled *bool `json:"enabled,omitempty"`
	EncryptionEnforcementMode *string `json:"encryptionEnforcementMode,omitempty"`
	KeyServerPriority *int64 `json:"keyServerPriority,omitempty"`
	PskConfigurations []ManaV2PskConfiguration `json:"pskConfigurations,omitempty"`
	SakConfigurations []ManaV2SakConfiguration `json:"sakConfigurations,omitempty"`
	SplitSakConfigByLagMember *bool `json:"splitSakConfigByLagMember,omitempty"`
	TransparentVlan *bool `json:"transparentVlan,omitempty"`
}

// NewManaV2InterfaceMaCsec instantiates a new ManaV2InterfaceMaCsec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2InterfaceMaCsec() *ManaV2InterfaceMaCsec {
	this := ManaV2InterfaceMaCsec{}
	return &this
}

// NewManaV2InterfaceMaCsecWithDefaults instantiates a new ManaV2InterfaceMaCsec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2InterfaceMaCsecWithDefaults() *ManaV2InterfaceMaCsec {
	this := ManaV2InterfaceMaCsec{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ManaV2InterfaceMaCsec) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2InterfaceMaCsec) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ManaV2InterfaceMaCsec) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ManaV2InterfaceMaCsec) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetEncryptionEnforcementMode returns the EncryptionEnforcementMode field value if set, zero value otherwise.
func (o *ManaV2InterfaceMaCsec) GetEncryptionEnforcementMode() string {
	if o == nil || IsNil(o.EncryptionEnforcementMode) {
		var ret string
		return ret
	}
	return *o.EncryptionEnforcementMode
}

// GetEncryptionEnforcementModeOk returns a tuple with the EncryptionEnforcementMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2InterfaceMaCsec) GetEncryptionEnforcementModeOk() (*string, bool) {
	if o == nil || IsNil(o.EncryptionEnforcementMode) {
		return nil, false
	}
	return o.EncryptionEnforcementMode, true
}

// HasEncryptionEnforcementMode returns a boolean if a field has been set.
func (o *ManaV2InterfaceMaCsec) HasEncryptionEnforcementMode() bool {
	if o != nil && !IsNil(o.EncryptionEnforcementMode) {
		return true
	}

	return false
}

// SetEncryptionEnforcementMode gets a reference to the given string and assigns it to the EncryptionEnforcementMode field.
func (o *ManaV2InterfaceMaCsec) SetEncryptionEnforcementMode(v string) {
	o.EncryptionEnforcementMode = &v
}

// GetKeyServerPriority returns the KeyServerPriority field value if set, zero value otherwise.
func (o *ManaV2InterfaceMaCsec) GetKeyServerPriority() int64 {
	if o == nil || IsNil(o.KeyServerPriority) {
		var ret int64
		return ret
	}
	return *o.KeyServerPriority
}

// GetKeyServerPriorityOk returns a tuple with the KeyServerPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2InterfaceMaCsec) GetKeyServerPriorityOk() (*int64, bool) {
	if o == nil || IsNil(o.KeyServerPriority) {
		return nil, false
	}
	return o.KeyServerPriority, true
}

// HasKeyServerPriority returns a boolean if a field has been set.
func (o *ManaV2InterfaceMaCsec) HasKeyServerPriority() bool {
	if o != nil && !IsNil(o.KeyServerPriority) {
		return true
	}

	return false
}

// SetKeyServerPriority gets a reference to the given int64 and assigns it to the KeyServerPriority field.
func (o *ManaV2InterfaceMaCsec) SetKeyServerPriority(v int64) {
	o.KeyServerPriority = &v
}

// GetPskConfigurations returns the PskConfigurations field value if set, zero value otherwise.
func (o *ManaV2InterfaceMaCsec) GetPskConfigurations() []ManaV2PskConfiguration {
	if o == nil || IsNil(o.PskConfigurations) {
		var ret []ManaV2PskConfiguration
		return ret
	}
	return o.PskConfigurations
}

// GetPskConfigurationsOk returns a tuple with the PskConfigurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2InterfaceMaCsec) GetPskConfigurationsOk() ([]ManaV2PskConfiguration, bool) {
	if o == nil || IsNil(o.PskConfigurations) {
		return nil, false
	}
	return o.PskConfigurations, true
}

// HasPskConfigurations returns a boolean if a field has been set.
func (o *ManaV2InterfaceMaCsec) HasPskConfigurations() bool {
	if o != nil && !IsNil(o.PskConfigurations) {
		return true
	}

	return false
}

// SetPskConfigurations gets a reference to the given []ManaV2PskConfiguration and assigns it to the PskConfigurations field.
func (o *ManaV2InterfaceMaCsec) SetPskConfigurations(v []ManaV2PskConfiguration) {
	o.PskConfigurations = v
}

// GetSakConfigurations returns the SakConfigurations field value if set, zero value otherwise.
func (o *ManaV2InterfaceMaCsec) GetSakConfigurations() []ManaV2SakConfiguration {
	if o == nil || IsNil(o.SakConfigurations) {
		var ret []ManaV2SakConfiguration
		return ret
	}
	return o.SakConfigurations
}

// GetSakConfigurationsOk returns a tuple with the SakConfigurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2InterfaceMaCsec) GetSakConfigurationsOk() ([]ManaV2SakConfiguration, bool) {
	if o == nil || IsNil(o.SakConfigurations) {
		return nil, false
	}
	return o.SakConfigurations, true
}

// HasSakConfigurations returns a boolean if a field has been set.
func (o *ManaV2InterfaceMaCsec) HasSakConfigurations() bool {
	if o != nil && !IsNil(o.SakConfigurations) {
		return true
	}

	return false
}

// SetSakConfigurations gets a reference to the given []ManaV2SakConfiguration and assigns it to the SakConfigurations field.
func (o *ManaV2InterfaceMaCsec) SetSakConfigurations(v []ManaV2SakConfiguration) {
	o.SakConfigurations = v
}

// GetSplitSakConfigByLagMember returns the SplitSakConfigByLagMember field value if set, zero value otherwise.
func (o *ManaV2InterfaceMaCsec) GetSplitSakConfigByLagMember() bool {
	if o == nil || IsNil(o.SplitSakConfigByLagMember) {
		var ret bool
		return ret
	}
	return *o.SplitSakConfigByLagMember
}

// GetSplitSakConfigByLagMemberOk returns a tuple with the SplitSakConfigByLagMember field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2InterfaceMaCsec) GetSplitSakConfigByLagMemberOk() (*bool, bool) {
	if o == nil || IsNil(o.SplitSakConfigByLagMember) {
		return nil, false
	}
	return o.SplitSakConfigByLagMember, true
}

// HasSplitSakConfigByLagMember returns a boolean if a field has been set.
func (o *ManaV2InterfaceMaCsec) HasSplitSakConfigByLagMember() bool {
	if o != nil && !IsNil(o.SplitSakConfigByLagMember) {
		return true
	}

	return false
}

// SetSplitSakConfigByLagMember gets a reference to the given bool and assigns it to the SplitSakConfigByLagMember field.
func (o *ManaV2InterfaceMaCsec) SetSplitSakConfigByLagMember(v bool) {
	o.SplitSakConfigByLagMember = &v
}

// GetTransparentVlan returns the TransparentVlan field value if set, zero value otherwise.
func (o *ManaV2InterfaceMaCsec) GetTransparentVlan() bool {
	if o == nil || IsNil(o.TransparentVlan) {
		var ret bool
		return ret
	}
	return *o.TransparentVlan
}

// GetTransparentVlanOk returns a tuple with the TransparentVlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2InterfaceMaCsec) GetTransparentVlanOk() (*bool, bool) {
	if o == nil || IsNil(o.TransparentVlan) {
		return nil, false
	}
	return o.TransparentVlan, true
}

// HasTransparentVlan returns a boolean if a field has been set.
func (o *ManaV2InterfaceMaCsec) HasTransparentVlan() bool {
	if o != nil && !IsNil(o.TransparentVlan) {
		return true
	}

	return false
}

// SetTransparentVlan gets a reference to the given bool and assigns it to the TransparentVlan field.
func (o *ManaV2InterfaceMaCsec) SetTransparentVlan(v bool) {
	o.TransparentVlan = &v
}

func (o ManaV2InterfaceMaCsec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2InterfaceMaCsec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.EncryptionEnforcementMode) {
		toSerialize["encryptionEnforcementMode"] = o.EncryptionEnforcementMode
	}
	if !IsNil(o.KeyServerPriority) {
		toSerialize["keyServerPriority"] = o.KeyServerPriority
	}
	if !IsNil(o.PskConfigurations) {
		toSerialize["pskConfigurations"] = o.PskConfigurations
	}
	if !IsNil(o.SakConfigurations) {
		toSerialize["sakConfigurations"] = o.SakConfigurations
	}
	if !IsNil(o.SplitSakConfigByLagMember) {
		toSerialize["splitSakConfigByLagMember"] = o.SplitSakConfigByLagMember
	}
	if !IsNil(o.TransparentVlan) {
		toSerialize["transparentVlan"] = o.TransparentVlan
	}
	return toSerialize, nil
}

type NullableManaV2InterfaceMaCsec struct {
	value *ManaV2InterfaceMaCsec
	isSet bool
}

func (v NullableManaV2InterfaceMaCsec) Get() *ManaV2InterfaceMaCsec {
	return v.value
}

func (v *NullableManaV2InterfaceMaCsec) Set(val *ManaV2InterfaceMaCsec) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2InterfaceMaCsec) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2InterfaceMaCsec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2InterfaceMaCsec(val *ManaV2InterfaceMaCsec) *NullableManaV2InterfaceMaCsec {
	return &NullableManaV2InterfaceMaCsec{value: val, isSet: true}
}

func (v NullableManaV2InterfaceMaCsec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2InterfaceMaCsec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


