/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AlertserviceZendeskDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertserviceZendeskDetails{}

// AlertserviceZendeskDetails struct for AlertserviceZendeskDetails
type AlertserviceZendeskDetails struct {
	// zendesk api token (required)
	ZendeskApiToken string `json:"zendeskApiToken"`
	// zendesk assignee id (required)
	ZendeskAssigneeId string `json:"zendeskAssigneeId"`
	// zendesk base url (required)
	ZendeskBaseUrl string `json:"zendeskBaseUrl"`
	// zendesk email (required)
	ZendeskEmail string `json:"zendeskEmail"`
}

type _AlertserviceZendeskDetails AlertserviceZendeskDetails

// NewAlertserviceZendeskDetails instantiates a new AlertserviceZendeskDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertserviceZendeskDetails(zendeskApiToken string, zendeskAssigneeId string, zendeskBaseUrl string, zendeskEmail string) *AlertserviceZendeskDetails {
	this := AlertserviceZendeskDetails{}
	this.ZendeskApiToken = zendeskApiToken
	this.ZendeskAssigneeId = zendeskAssigneeId
	this.ZendeskBaseUrl = zendeskBaseUrl
	this.ZendeskEmail = zendeskEmail
	return &this
}

// NewAlertserviceZendeskDetailsWithDefaults instantiates a new AlertserviceZendeskDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertserviceZendeskDetailsWithDefaults() *AlertserviceZendeskDetails {
	this := AlertserviceZendeskDetails{}
	return &this
}

// GetZendeskApiToken returns the ZendeskApiToken field value
func (o *AlertserviceZendeskDetails) GetZendeskApiToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZendeskApiToken
}

// GetZendeskApiTokenOk returns a tuple with the ZendeskApiToken field value
// and a boolean to check if the value has been set.
func (o *AlertserviceZendeskDetails) GetZendeskApiTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZendeskApiToken, true
}

// SetZendeskApiToken sets field value
func (o *AlertserviceZendeskDetails) SetZendeskApiToken(v string) {
	o.ZendeskApiToken = v
}

// GetZendeskAssigneeId returns the ZendeskAssigneeId field value
func (o *AlertserviceZendeskDetails) GetZendeskAssigneeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZendeskAssigneeId
}

// GetZendeskAssigneeIdOk returns a tuple with the ZendeskAssigneeId field value
// and a boolean to check if the value has been set.
func (o *AlertserviceZendeskDetails) GetZendeskAssigneeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZendeskAssigneeId, true
}

// SetZendeskAssigneeId sets field value
func (o *AlertserviceZendeskDetails) SetZendeskAssigneeId(v string) {
	o.ZendeskAssigneeId = v
}

// GetZendeskBaseUrl returns the ZendeskBaseUrl field value
func (o *AlertserviceZendeskDetails) GetZendeskBaseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZendeskBaseUrl
}

// GetZendeskBaseUrlOk returns a tuple with the ZendeskBaseUrl field value
// and a boolean to check if the value has been set.
func (o *AlertserviceZendeskDetails) GetZendeskBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZendeskBaseUrl, true
}

// SetZendeskBaseUrl sets field value
func (o *AlertserviceZendeskDetails) SetZendeskBaseUrl(v string) {
	o.ZendeskBaseUrl = v
}

// GetZendeskEmail returns the ZendeskEmail field value
func (o *AlertserviceZendeskDetails) GetZendeskEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZendeskEmail
}

// GetZendeskEmailOk returns a tuple with the ZendeskEmail field value
// and a boolean to check if the value has been set.
func (o *AlertserviceZendeskDetails) GetZendeskEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZendeskEmail, true
}

// SetZendeskEmail sets field value
func (o *AlertserviceZendeskDetails) SetZendeskEmail(v string) {
	o.ZendeskEmail = v
}

func (o AlertserviceZendeskDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertserviceZendeskDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["zendeskApiToken"] = o.ZendeskApiToken
	toSerialize["zendeskAssigneeId"] = o.ZendeskAssigneeId
	toSerialize["zendeskBaseUrl"] = o.ZendeskBaseUrl
	toSerialize["zendeskEmail"] = o.ZendeskEmail
	return toSerialize, nil
}

func (o *AlertserviceZendeskDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zendeskApiToken",
		"zendeskAssigneeId",
		"zendeskBaseUrl",
		"zendeskEmail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlertserviceZendeskDetails := _AlertserviceZendeskDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlertserviceZendeskDetails)

	if err != nil {
		return err
	}

	*o = AlertserviceZendeskDetails(varAlertserviceZendeskDetails)

	return err
}

type NullableAlertserviceZendeskDetails struct {
	value *AlertserviceZendeskDetails
	isSet bool
}

func (v NullableAlertserviceZendeskDetails) Get() *AlertserviceZendeskDetails {
	return v.value
}

func (v *NullableAlertserviceZendeskDetails) Set(val *AlertserviceZendeskDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertserviceZendeskDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertserviceZendeskDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertserviceZendeskDetails(val *AlertserviceZendeskDetails) *NullableAlertserviceZendeskDetails {
	return &NullableAlertserviceZendeskDetails{value: val, isSet: true}
}

func (v NullableAlertserviceZendeskDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertserviceZendeskDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


