/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceReadDnsproxyListGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceReadDnsproxyListGetResponse{}

// V2AssuranceReadDnsproxyListGetResponse struct for V2AssuranceReadDnsproxyListGetResponse
type V2AssuranceReadDnsproxyListGetResponse struct {
	DnsproxyList []AssuranceDnsProxyEntry `json:"dnsproxyList,omitempty"`
}

// NewV2AssuranceReadDnsproxyListGetResponse instantiates a new V2AssuranceReadDnsproxyListGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceReadDnsproxyListGetResponse() *V2AssuranceReadDnsproxyListGetResponse {
	this := V2AssuranceReadDnsproxyListGetResponse{}
	return &this
}

// NewV2AssuranceReadDnsproxyListGetResponseWithDefaults instantiates a new V2AssuranceReadDnsproxyListGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceReadDnsproxyListGetResponseWithDefaults() *V2AssuranceReadDnsproxyListGetResponse {
	this := V2AssuranceReadDnsproxyListGetResponse{}
	return &this
}

// GetDnsproxyList returns the DnsproxyList field value if set, zero value otherwise.
func (o *V2AssuranceReadDnsproxyListGetResponse) GetDnsproxyList() []AssuranceDnsProxyEntry {
	if o == nil || IsNil(o.DnsproxyList) {
		var ret []AssuranceDnsProxyEntry
		return ret
	}
	return o.DnsproxyList
}

// GetDnsproxyListOk returns a tuple with the DnsproxyList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceReadDnsproxyListGetResponse) GetDnsproxyListOk() ([]AssuranceDnsProxyEntry, bool) {
	if o == nil || IsNil(o.DnsproxyList) {
		return nil, false
	}
	return o.DnsproxyList, true
}

// HasDnsproxyList returns a boolean if a field has been set.
func (o *V2AssuranceReadDnsproxyListGetResponse) HasDnsproxyList() bool {
	if o != nil && !IsNil(o.DnsproxyList) {
		return true
	}

	return false
}

// SetDnsproxyList gets a reference to the given []AssuranceDnsProxyEntry and assigns it to the DnsproxyList field.
func (o *V2AssuranceReadDnsproxyListGetResponse) SetDnsproxyList(v []AssuranceDnsProxyEntry) {
	o.DnsproxyList = v
}

func (o V2AssuranceReadDnsproxyListGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceReadDnsproxyListGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DnsproxyList) {
		toSerialize["dnsproxyList"] = o.DnsproxyList
	}
	return toSerialize, nil
}

type NullableV2AssuranceReadDnsproxyListGetResponse struct {
	value *V2AssuranceReadDnsproxyListGetResponse
	isSet bool
}

func (v NullableV2AssuranceReadDnsproxyListGetResponse) Get() *V2AssuranceReadDnsproxyListGetResponse {
	return v.value
}

func (v *NullableV2AssuranceReadDnsproxyListGetResponse) Set(val *V2AssuranceReadDnsproxyListGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceReadDnsproxyListGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceReadDnsproxyListGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceReadDnsproxyListGetResponse(val *V2AssuranceReadDnsproxyListGetResponse) *NullableV2AssuranceReadDnsproxyListGetResponse {
	return &NullableV2AssuranceReadDnsproxyListGetResponse{value: val, isSet: true}
}

func (v NullableV2AssuranceReadDnsproxyListGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceReadDnsproxyListGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


