/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1AuthLoginPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AuthLoginPostResponse{}

// V1AuthLoginPostResponse struct for V1AuthLoginPostResponse
type V1AuthLoginPostResponse struct {
	Auth *bool `json:"auth,omitempty"`
	Token *string `json:"token,omitempty"`
	AccountType *string `json:"accountType,omitempty"`
	// User email address (returned for MFA users)
	Email *string `json:"email,omitempty"`
	// MFA type (returned for MFA users)
	MfaType *string `json:"mfaType,omitempty"`
	// State token for MFA verification (returned for MFA users)
	StateToken *string `json:"stateToken,omitempty"`
	// Authentication status (returned for MFA users)
	Status *string `json:"status,omitempty"`
}

// NewV1AuthLoginPostResponse instantiates a new V1AuthLoginPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AuthLoginPostResponse() *V1AuthLoginPostResponse {
	this := V1AuthLoginPostResponse{}
	return &this
}

// NewV1AuthLoginPostResponseWithDefaults instantiates a new V1AuthLoginPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AuthLoginPostResponseWithDefaults() *V1AuthLoginPostResponse {
	this := V1AuthLoginPostResponse{}
	return &this
}

// GetAuth returns the Auth field value if set, zero value otherwise.
func (o *V1AuthLoginPostResponse) GetAuth() bool {
	if o == nil || IsNil(o.Auth) {
		var ret bool
		return ret
	}
	return *o.Auth
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthLoginPostResponse) GetAuthOk() (*bool, bool) {
	if o == nil || IsNil(o.Auth) {
		return nil, false
	}
	return o.Auth, true
}

// HasAuth returns a boolean if a field has been set.
func (o *V1AuthLoginPostResponse) HasAuth() bool {
	if o != nil && !IsNil(o.Auth) {
		return true
	}

	return false
}

// SetAuth gets a reference to the given bool and assigns it to the Auth field.
func (o *V1AuthLoginPostResponse) SetAuth(v bool) {
	o.Auth = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *V1AuthLoginPostResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthLoginPostResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *V1AuthLoginPostResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *V1AuthLoginPostResponse) SetToken(v string) {
	o.Token = &v
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *V1AuthLoginPostResponse) GetAccountType() string {
	if o == nil || IsNil(o.AccountType) {
		var ret string
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthLoginPostResponse) GetAccountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AccountType) {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *V1AuthLoginPostResponse) HasAccountType() bool {
	if o != nil && !IsNil(o.AccountType) {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given string and assigns it to the AccountType field.
func (o *V1AuthLoginPostResponse) SetAccountType(v string) {
	o.AccountType = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *V1AuthLoginPostResponse) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthLoginPostResponse) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *V1AuthLoginPostResponse) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *V1AuthLoginPostResponse) SetEmail(v string) {
	o.Email = &v
}

// GetMfaType returns the MfaType field value if set, zero value otherwise.
func (o *V1AuthLoginPostResponse) GetMfaType() string {
	if o == nil || IsNil(o.MfaType) {
		var ret string
		return ret
	}
	return *o.MfaType
}

// GetMfaTypeOk returns a tuple with the MfaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthLoginPostResponse) GetMfaTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MfaType) {
		return nil, false
	}
	return o.MfaType, true
}

// HasMfaType returns a boolean if a field has been set.
func (o *V1AuthLoginPostResponse) HasMfaType() bool {
	if o != nil && !IsNil(o.MfaType) {
		return true
	}

	return false
}

// SetMfaType gets a reference to the given string and assigns it to the MfaType field.
func (o *V1AuthLoginPostResponse) SetMfaType(v string) {
	o.MfaType = &v
}

// GetStateToken returns the StateToken field value if set, zero value otherwise.
func (o *V1AuthLoginPostResponse) GetStateToken() string {
	if o == nil || IsNil(o.StateToken) {
		var ret string
		return ret
	}
	return *o.StateToken
}

// GetStateTokenOk returns a tuple with the StateToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthLoginPostResponse) GetStateTokenOk() (*string, bool) {
	if o == nil || IsNil(o.StateToken) {
		return nil, false
	}
	return o.StateToken, true
}

// HasStateToken returns a boolean if a field has been set.
func (o *V1AuthLoginPostResponse) HasStateToken() bool {
	if o != nil && !IsNil(o.StateToken) {
		return true
	}

	return false
}

// SetStateToken gets a reference to the given string and assigns it to the StateToken field.
func (o *V1AuthLoginPostResponse) SetStateToken(v string) {
	o.StateToken = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1AuthLoginPostResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthLoginPostResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1AuthLoginPostResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1AuthLoginPostResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1AuthLoginPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AuthLoginPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Auth) {
		toSerialize["auth"] = o.Auth
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.AccountType) {
		toSerialize["accountType"] = o.AccountType
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.MfaType) {
		toSerialize["mfaType"] = o.MfaType
	}
	if !IsNil(o.StateToken) {
		toSerialize["stateToken"] = o.StateToken
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1AuthLoginPostResponse struct {
	value *V1AuthLoginPostResponse
	isSet bool
}

func (v NullableV1AuthLoginPostResponse) Get() *V1AuthLoginPostResponse {
	return v.value
}

func (v *NullableV1AuthLoginPostResponse) Set(val *V1AuthLoginPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AuthLoginPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AuthLoginPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AuthLoginPostResponse(val *V1AuthLoginPostResponse) *NullableV1AuthLoginPostResponse {
	return &NullableV1AuthLoginPostResponse{value: val, isSet: true}
}

func (v NullableV1AuthLoginPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AuthLoginPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


