/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceCreateDnsproxyEntryPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceCreateDnsproxyEntryPostRequest{}

// V2AssuranceCreateDnsproxyEntryPostRequest struct for V2AssuranceCreateDnsproxyEntryPostRequest
type V2AssuranceCreateDnsproxyEntryPostRequest struct {
	DnsproxyEntry *AssuranceDnsProxyEntry `json:"dnsproxyEntry,omitempty"`
}

// NewV2AssuranceCreateDnsproxyEntryPostRequest instantiates a new V2AssuranceCreateDnsproxyEntryPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceCreateDnsproxyEntryPostRequest() *V2AssuranceCreateDnsproxyEntryPostRequest {
	this := V2AssuranceCreateDnsproxyEntryPostRequest{}
	return &this
}

// NewV2AssuranceCreateDnsproxyEntryPostRequestWithDefaults instantiates a new V2AssuranceCreateDnsproxyEntryPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceCreateDnsproxyEntryPostRequestWithDefaults() *V2AssuranceCreateDnsproxyEntryPostRequest {
	this := V2AssuranceCreateDnsproxyEntryPostRequest{}
	return &this
}

// GetDnsproxyEntry returns the DnsproxyEntry field value if set, zero value otherwise.
func (o *V2AssuranceCreateDnsproxyEntryPostRequest) GetDnsproxyEntry() AssuranceDnsProxyEntry {
	if o == nil || IsNil(o.DnsproxyEntry) {
		var ret AssuranceDnsProxyEntry
		return ret
	}
	return *o.DnsproxyEntry
}

// GetDnsproxyEntryOk returns a tuple with the DnsproxyEntry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceCreateDnsproxyEntryPostRequest) GetDnsproxyEntryOk() (*AssuranceDnsProxyEntry, bool) {
	if o == nil || IsNil(o.DnsproxyEntry) {
		return nil, false
	}
	return o.DnsproxyEntry, true
}

// HasDnsproxyEntry returns a boolean if a field has been set.
func (o *V2AssuranceCreateDnsproxyEntryPostRequest) HasDnsproxyEntry() bool {
	if o != nil && !IsNil(o.DnsproxyEntry) {
		return true
	}

	return false
}

// SetDnsproxyEntry gets a reference to the given AssuranceDnsProxyEntry and assigns it to the DnsproxyEntry field.
func (o *V2AssuranceCreateDnsproxyEntryPostRequest) SetDnsproxyEntry(v AssuranceDnsProxyEntry) {
	o.DnsproxyEntry = &v
}

func (o V2AssuranceCreateDnsproxyEntryPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceCreateDnsproxyEntryPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DnsproxyEntry) {
		toSerialize["dnsproxyEntry"] = o.DnsproxyEntry
	}
	return toSerialize, nil
}

type NullableV2AssuranceCreateDnsproxyEntryPostRequest struct {
	value *V2AssuranceCreateDnsproxyEntryPostRequest
	isSet bool
}

func (v NullableV2AssuranceCreateDnsproxyEntryPostRequest) Get() *V2AssuranceCreateDnsproxyEntryPostRequest {
	return v.value
}

func (v *NullableV2AssuranceCreateDnsproxyEntryPostRequest) Set(val *V2AssuranceCreateDnsproxyEntryPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceCreateDnsproxyEntryPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceCreateDnsproxyEntryPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceCreateDnsproxyEntryPostRequest(val *V2AssuranceCreateDnsproxyEntryPostRequest) *NullableV2AssuranceCreateDnsproxyEntryPostRequest {
	return &NullableV2AssuranceCreateDnsproxyEntryPostRequest{value: val, isSet: true}
}

func (v NullableV2AssuranceCreateDnsproxyEntryPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceCreateDnsproxyEntryPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


