/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2SlaConformance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2SlaConformance{}

// ManaV2SlaConformance struct for ManaV2SlaConformance
type ManaV2SlaConformance struct {
	DampeningFactor *int64 `json:"dampeningFactor,omitempty"`
	Duration *int64 `json:"duration,omitempty"`
	Interval *int64 `json:"interval,omitempty"`
}

// NewManaV2SlaConformance instantiates a new ManaV2SlaConformance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2SlaConformance() *ManaV2SlaConformance {
	this := ManaV2SlaConformance{}
	return &this
}

// NewManaV2SlaConformanceWithDefaults instantiates a new ManaV2SlaConformance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2SlaConformanceWithDefaults() *ManaV2SlaConformance {
	this := ManaV2SlaConformance{}
	return &this
}

// GetDampeningFactor returns the DampeningFactor field value if set, zero value otherwise.
func (o *ManaV2SlaConformance) GetDampeningFactor() int64 {
	if o == nil || IsNil(o.DampeningFactor) {
		var ret int64
		return ret
	}
	return *o.DampeningFactor
}

// GetDampeningFactorOk returns a tuple with the DampeningFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SlaConformance) GetDampeningFactorOk() (*int64, bool) {
	if o == nil || IsNil(o.DampeningFactor) {
		return nil, false
	}
	return o.DampeningFactor, true
}

// HasDampeningFactor returns a boolean if a field has been set.
func (o *ManaV2SlaConformance) HasDampeningFactor() bool {
	if o != nil && !IsNil(o.DampeningFactor) {
		return true
	}

	return false
}

// SetDampeningFactor gets a reference to the given int64 and assigns it to the DampeningFactor field.
func (o *ManaV2SlaConformance) SetDampeningFactor(v int64) {
	o.DampeningFactor = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *ManaV2SlaConformance) GetDuration() int64 {
	if o == nil || IsNil(o.Duration) {
		var ret int64
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SlaConformance) GetDurationOk() (*int64, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *ManaV2SlaConformance) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int64 and assigns it to the Duration field.
func (o *ManaV2SlaConformance) SetDuration(v int64) {
	o.Duration = &v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *ManaV2SlaConformance) GetInterval() int64 {
	if o == nil || IsNil(o.Interval) {
		var ret int64
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SlaConformance) GetIntervalOk() (*int64, bool) {
	if o == nil || IsNil(o.Interval) {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *ManaV2SlaConformance) HasInterval() bool {
	if o != nil && !IsNil(o.Interval) {
		return true
	}

	return false
}

// SetInterval gets a reference to the given int64 and assigns it to the Interval field.
func (o *ManaV2SlaConformance) SetInterval(v int64) {
	o.Interval = &v
}

func (o ManaV2SlaConformance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2SlaConformance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DampeningFactor) {
		toSerialize["dampeningFactor"] = o.DampeningFactor
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.Interval) {
		toSerialize["interval"] = o.Interval
	}
	return toSerialize, nil
}

type NullableManaV2SlaConformance struct {
	value *ManaV2SlaConformance
	isSet bool
}

func (v NullableManaV2SlaConformance) Get() *ManaV2SlaConformance {
	return v.value
}

func (v *NullableManaV2SlaConformance) Set(val *ManaV2SlaConformance) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2SlaConformance) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2SlaConformance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2SlaConformance(val *ManaV2SlaConformance) *NullableManaV2SlaConformance {
	return &NullableManaV2SlaConformance{value: val, isSet: true}
}

func (v NullableManaV2SlaConformance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2SlaConformance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


