/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1UsersPasswordsExpirePostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1UsersPasswordsExpirePostResponse{}

// V1UsersPasswordsExpirePostResponse struct for V1UsersPasswordsExpirePostResponse
type V1UsersPasswordsExpirePostResponse struct {
	FailedCount *int32 `json:"failedCount,omitempty"`
	FailedUsers []IamFailedUser `json:"failedUsers,omitempty"`
	SuccessCount *int32 `json:"successCount,omitempty"`
}

// NewV1UsersPasswordsExpirePostResponse instantiates a new V1UsersPasswordsExpirePostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1UsersPasswordsExpirePostResponse() *V1UsersPasswordsExpirePostResponse {
	this := V1UsersPasswordsExpirePostResponse{}
	return &this
}

// NewV1UsersPasswordsExpirePostResponseWithDefaults instantiates a new V1UsersPasswordsExpirePostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1UsersPasswordsExpirePostResponseWithDefaults() *V1UsersPasswordsExpirePostResponse {
	this := V1UsersPasswordsExpirePostResponse{}
	return &this
}

// GetFailedCount returns the FailedCount field value if set, zero value otherwise.
func (o *V1UsersPasswordsExpirePostResponse) GetFailedCount() int32 {
	if o == nil || IsNil(o.FailedCount) {
		var ret int32
		return ret
	}
	return *o.FailedCount
}

// GetFailedCountOk returns a tuple with the FailedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UsersPasswordsExpirePostResponse) GetFailedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedCount) {
		return nil, false
	}
	return o.FailedCount, true
}

// HasFailedCount returns a boolean if a field has been set.
func (o *V1UsersPasswordsExpirePostResponse) HasFailedCount() bool {
	if o != nil && !IsNil(o.FailedCount) {
		return true
	}

	return false
}

// SetFailedCount gets a reference to the given int32 and assigns it to the FailedCount field.
func (o *V1UsersPasswordsExpirePostResponse) SetFailedCount(v int32) {
	o.FailedCount = &v
}

// GetFailedUsers returns the FailedUsers field value if set, zero value otherwise.
func (o *V1UsersPasswordsExpirePostResponse) GetFailedUsers() []IamFailedUser {
	if o == nil || IsNil(o.FailedUsers) {
		var ret []IamFailedUser
		return ret
	}
	return o.FailedUsers
}

// GetFailedUsersOk returns a tuple with the FailedUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UsersPasswordsExpirePostResponse) GetFailedUsersOk() ([]IamFailedUser, bool) {
	if o == nil || IsNil(o.FailedUsers) {
		return nil, false
	}
	return o.FailedUsers, true
}

// HasFailedUsers returns a boolean if a field has been set.
func (o *V1UsersPasswordsExpirePostResponse) HasFailedUsers() bool {
	if o != nil && !IsNil(o.FailedUsers) {
		return true
	}

	return false
}

// SetFailedUsers gets a reference to the given []IamFailedUser and assigns it to the FailedUsers field.
func (o *V1UsersPasswordsExpirePostResponse) SetFailedUsers(v []IamFailedUser) {
	o.FailedUsers = v
}

// GetSuccessCount returns the SuccessCount field value if set, zero value otherwise.
func (o *V1UsersPasswordsExpirePostResponse) GetSuccessCount() int32 {
	if o == nil || IsNil(o.SuccessCount) {
		var ret int32
		return ret
	}
	return *o.SuccessCount
}

// GetSuccessCountOk returns a tuple with the SuccessCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UsersPasswordsExpirePostResponse) GetSuccessCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SuccessCount) {
		return nil, false
	}
	return o.SuccessCount, true
}

// HasSuccessCount returns a boolean if a field has been set.
func (o *V1UsersPasswordsExpirePostResponse) HasSuccessCount() bool {
	if o != nil && !IsNil(o.SuccessCount) {
		return true
	}

	return false
}

// SetSuccessCount gets a reference to the given int32 and assigns it to the SuccessCount field.
func (o *V1UsersPasswordsExpirePostResponse) SetSuccessCount(v int32) {
	o.SuccessCount = &v
}

func (o V1UsersPasswordsExpirePostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1UsersPasswordsExpirePostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FailedCount) {
		toSerialize["failedCount"] = o.FailedCount
	}
	if !IsNil(o.FailedUsers) {
		toSerialize["failedUsers"] = o.FailedUsers
	}
	if !IsNil(o.SuccessCount) {
		toSerialize["successCount"] = o.SuccessCount
	}
	return toSerialize, nil
}

type NullableV1UsersPasswordsExpirePostResponse struct {
	value *V1UsersPasswordsExpirePostResponse
	isSet bool
}

func (v NullableV1UsersPasswordsExpirePostResponse) Get() *V1UsersPasswordsExpirePostResponse {
	return v.value
}

func (v *NullableV1UsersPasswordsExpirePostResponse) Set(val *V1UsersPasswordsExpirePostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1UsersPasswordsExpirePostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1UsersPasswordsExpirePostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1UsersPasswordsExpirePostResponse(val *V1UsersPasswordsExpirePostResponse) *NullableV1UsersPasswordsExpirePostResponse {
	return &NullableV1UsersPasswordsExpirePostResponse{value: val, isSet: true}
}

func (v NullableV1UsersPasswordsExpirePostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1UsersPasswordsExpirePostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


