/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse{}

// V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse struct for V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse
type V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse struct {
	Status *string `json:"status,omitempty"`
}

// NewV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse instantiates a new V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse() *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse {
	this := V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse{}
	return &this
}

// NewV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponseWithDefaults instantiates a new V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponseWithDefaults() *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse {
	this := V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse struct {
	value *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse
	isSet bool
}

func (v NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) Get() *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse {
	return v.value
}

func (v *NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) Set(val *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse(val *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) *NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse {
	return &NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


