/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest{}

// V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest struct for V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest
type V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest struct {
	// match ID for the customer's service subscription (required)
	Id int64 `json:"id"`
	// Customer’s service status: Paused or Active (required)
	Status string `json:"status"`
}

type _V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest

// NewV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest instantiates a new V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest(id int64, status string) *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest {
	this := V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest{}
	this.Id = id
	this.Status = status
	return &this
}

// NewV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequestWithDefaults instantiates a new V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequestWithDefaults() *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest {
	this := V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest{}
	return &this
}

// GetId returns the Id field value
func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) SetId(v int64) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) SetStatus(v string) {
	o.Status = v
}

func (o V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest := _V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest)

	if err != nil {
		return err
	}

	*o = V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest(varV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest)

	return err
}

type NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest struct {
	value *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest
	isSet bool
}

func (v NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) Get() *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest {
	return v.value
}

func (v *NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) Set(val *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest(val *V1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) *NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest {
	return &NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetsB2bPeeringMatchServiceToCustomerServiceStatusPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


