/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceCreateDnsproxyEntryPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceCreateDnsproxyEntryPostResponse{}

// V2AssuranceCreateDnsproxyEntryPostResponse struct for V2AssuranceCreateDnsproxyEntryPostResponse
type V2AssuranceCreateDnsproxyEntryPostResponse struct {
	// dns proxy table entry id (required)
	DnsproxyEntryId *string `json:"dnsproxyEntryId,omitempty"`
}

// NewV2AssuranceCreateDnsproxyEntryPostResponse instantiates a new V2AssuranceCreateDnsproxyEntryPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceCreateDnsproxyEntryPostResponse() *V2AssuranceCreateDnsproxyEntryPostResponse {
	this := V2AssuranceCreateDnsproxyEntryPostResponse{}
	return &this
}

// NewV2AssuranceCreateDnsproxyEntryPostResponseWithDefaults instantiates a new V2AssuranceCreateDnsproxyEntryPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceCreateDnsproxyEntryPostResponseWithDefaults() *V2AssuranceCreateDnsproxyEntryPostResponse {
	this := V2AssuranceCreateDnsproxyEntryPostResponse{}
	return &this
}

// GetDnsproxyEntryId returns the DnsproxyEntryId field value if set, zero value otherwise.
func (o *V2AssuranceCreateDnsproxyEntryPostResponse) GetDnsproxyEntryId() string {
	if o == nil || IsNil(o.DnsproxyEntryId) {
		var ret string
		return ret
	}
	return *o.DnsproxyEntryId
}

// GetDnsproxyEntryIdOk returns a tuple with the DnsproxyEntryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceCreateDnsproxyEntryPostResponse) GetDnsproxyEntryIdOk() (*string, bool) {
	if o == nil || IsNil(o.DnsproxyEntryId) {
		return nil, false
	}
	return o.DnsproxyEntryId, true
}

// HasDnsproxyEntryId returns a boolean if a field has been set.
func (o *V2AssuranceCreateDnsproxyEntryPostResponse) HasDnsproxyEntryId() bool {
	if o != nil && !IsNil(o.DnsproxyEntryId) {
		return true
	}

	return false
}

// SetDnsproxyEntryId gets a reference to the given string and assigns it to the DnsproxyEntryId field.
func (o *V2AssuranceCreateDnsproxyEntryPostResponse) SetDnsproxyEntryId(v string) {
	o.DnsproxyEntryId = &v
}

func (o V2AssuranceCreateDnsproxyEntryPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceCreateDnsproxyEntryPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DnsproxyEntryId) {
		toSerialize["dnsproxyEntryId"] = o.DnsproxyEntryId
	}
	return toSerialize, nil
}

type NullableV2AssuranceCreateDnsproxyEntryPostResponse struct {
	value *V2AssuranceCreateDnsproxyEntryPostResponse
	isSet bool
}

func (v NullableV2AssuranceCreateDnsproxyEntryPostResponse) Get() *V2AssuranceCreateDnsproxyEntryPostResponse {
	return v.value
}

func (v *NullableV2AssuranceCreateDnsproxyEntryPostResponse) Set(val *V2AssuranceCreateDnsproxyEntryPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceCreateDnsproxyEntryPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceCreateDnsproxyEntryPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceCreateDnsproxyEntryPostResponse(val *V2AssuranceCreateDnsproxyEntryPostResponse) *NullableV2AssuranceCreateDnsproxyEntryPostResponse {
	return &NullableV2AssuranceCreateDnsproxyEntryPostResponse{value: val, isSet: true}
}

func (v NullableV2AssuranceCreateDnsproxyEntryPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceCreateDnsproxyEntryPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


