/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2NullablePskConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2NullablePskConfiguration{}

// ManaV2NullablePskConfiguration struct for ManaV2NullablePskConfiguration
type ManaV2NullablePskConfiguration struct {
	Psk *ManaV2PskConfiguration `json:"psk,omitempty"`
}

// NewManaV2NullablePskConfiguration instantiates a new ManaV2NullablePskConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2NullablePskConfiguration() *ManaV2NullablePskConfiguration {
	this := ManaV2NullablePskConfiguration{}
	return &this
}

// NewManaV2NullablePskConfigurationWithDefaults instantiates a new ManaV2NullablePskConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2NullablePskConfigurationWithDefaults() *ManaV2NullablePskConfiguration {
	this := ManaV2NullablePskConfiguration{}
	return &this
}

// GetPsk returns the Psk field value if set, zero value otherwise.
func (o *ManaV2NullablePskConfiguration) GetPsk() ManaV2PskConfiguration {
	if o == nil || IsNil(o.Psk) {
		var ret ManaV2PskConfiguration
		return ret
	}
	return *o.Psk
}

// GetPskOk returns a tuple with the Psk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2NullablePskConfiguration) GetPskOk() (*ManaV2PskConfiguration, bool) {
	if o == nil || IsNil(o.Psk) {
		return nil, false
	}
	return o.Psk, true
}

// HasPsk returns a boolean if a field has been set.
func (o *ManaV2NullablePskConfiguration) HasPsk() bool {
	if o != nil && !IsNil(o.Psk) {
		return true
	}

	return false
}

// SetPsk gets a reference to the given ManaV2PskConfiguration and assigns it to the Psk field.
func (o *ManaV2NullablePskConfiguration) SetPsk(v ManaV2PskConfiguration) {
	o.Psk = &v
}

func (o ManaV2NullablePskConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2NullablePskConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Psk) {
		toSerialize["psk"] = o.Psk
	}
	return toSerialize, nil
}

type NullableManaV2NullablePskConfiguration struct {
	value *ManaV2NullablePskConfiguration
	isSet bool
}

func (v NullableManaV2NullablePskConfiguration) Get() *ManaV2NullablePskConfiguration {
	return v.value
}

func (v *NullableManaV2NullablePskConfiguration) Set(val *ManaV2NullablePskConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2NullablePskConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2NullablePskConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2NullablePskConfiguration(val *ManaV2NullablePskConfiguration) *NullableManaV2NullablePskConfiguration {
	return &NullableManaV2NullablePskConfiguration{value: val, isSet: true}
}

func (v NullableManaV2NullablePskConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2NullablePskConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


