/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the IamFailedUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IamFailedUser{}

// IamFailedUser struct for IamFailedUser
type IamFailedUser struct {
	Reason *string `json:"reason,omitempty"`
	UserId *string `json:"userId,omitempty"`
}

// NewIamFailedUser instantiates a new IamFailedUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIamFailedUser() *IamFailedUser {
	this := IamFailedUser{}
	return &this
}

// NewIamFailedUserWithDefaults instantiates a new IamFailedUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIamFailedUserWithDefaults() *IamFailedUser {
	this := IamFailedUser{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *IamFailedUser) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamFailedUser) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *IamFailedUser) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *IamFailedUser) SetReason(v string) {
	o.Reason = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *IamFailedUser) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamFailedUser) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *IamFailedUser) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *IamFailedUser) SetUserId(v string) {
	o.UserId = &v
}

func (o IamFailedUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IamFailedUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	return toSerialize, nil
}

type NullableIamFailedUser struct {
	value *IamFailedUser
	isSet bool
}

func (v NullableIamFailedUser) Get() *IamFailedUser {
	return v.value
}

func (v *NullableIamFailedUser) Set(val *IamFailedUser) {
	v.value = val
	v.isSet = true
}

func (v NullableIamFailedUser) IsSet() bool {
	return v.isSet
}

func (v *NullableIamFailedUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIamFailedUser(val *IamFailedUser) *NullableIamFailedUser {
	return &NullableIamFailedUser{value: val, isSet: true}
}

func (v NullableIamFailedUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIamFailedUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


