/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2NullableMaCsecConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2NullableMaCsecConfiguration{}

// ManaV2NullableMaCsecConfiguration struct for ManaV2NullableMaCsecConfiguration
type ManaV2NullableMaCsecConfiguration struct {
	Macsec *ManaV2MaCsecConfiguration `json:"macsec,omitempty"`
}

// NewManaV2NullableMaCsecConfiguration instantiates a new ManaV2NullableMaCsecConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2NullableMaCsecConfiguration() *ManaV2NullableMaCsecConfiguration {
	this := ManaV2NullableMaCsecConfiguration{}
	return &this
}

// NewManaV2NullableMaCsecConfigurationWithDefaults instantiates a new ManaV2NullableMaCsecConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2NullableMaCsecConfigurationWithDefaults() *ManaV2NullableMaCsecConfiguration {
	this := ManaV2NullableMaCsecConfiguration{}
	return &this
}

// GetMacsec returns the Macsec field value if set, zero value otherwise.
func (o *ManaV2NullableMaCsecConfiguration) GetMacsec() ManaV2MaCsecConfiguration {
	if o == nil || IsNil(o.Macsec) {
		var ret ManaV2MaCsecConfiguration
		return ret
	}
	return *o.Macsec
}

// GetMacsecOk returns a tuple with the Macsec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2NullableMaCsecConfiguration) GetMacsecOk() (*ManaV2MaCsecConfiguration, bool) {
	if o == nil || IsNil(o.Macsec) {
		return nil, false
	}
	return o.Macsec, true
}

// HasMacsec returns a boolean if a field has been set.
func (o *ManaV2NullableMaCsecConfiguration) HasMacsec() bool {
	if o != nil && !IsNil(o.Macsec) {
		return true
	}

	return false
}

// SetMacsec gets a reference to the given ManaV2MaCsecConfiguration and assigns it to the Macsec field.
func (o *ManaV2NullableMaCsecConfiguration) SetMacsec(v ManaV2MaCsecConfiguration) {
	o.Macsec = &v
}

func (o ManaV2NullableMaCsecConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2NullableMaCsecConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Macsec) {
		toSerialize["macsec"] = o.Macsec
	}
	return toSerialize, nil
}

type NullableManaV2NullableMaCsecConfiguration struct {
	value *ManaV2NullableMaCsecConfiguration
	isSet bool
}

func (v NullableManaV2NullableMaCsecConfiguration) Get() *ManaV2NullableMaCsecConfiguration {
	return v.value
}

func (v *NullableManaV2NullableMaCsecConfiguration) Set(val *ManaV2NullableMaCsecConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2NullableMaCsecConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2NullableMaCsecConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2NullableMaCsecConfiguration(val *ManaV2NullableMaCsecConfiguration) *NullableManaV2NullableMaCsecConfiguration {
	return &NullableManaV2NullableMaCsecConfiguration{value: val, isSet: true}
}

func (v NullableManaV2NullableMaCsecConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2NullableMaCsecConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


