/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2NullableSlaConformance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2NullableSlaConformance{}

// ManaV2NullableSlaConformance struct for ManaV2NullableSlaConformance
type ManaV2NullableSlaConformance struct {
	SlaConformance *ManaV2SlaConformance `json:"slaConformance,omitempty"`
}

// NewManaV2NullableSlaConformance instantiates a new ManaV2NullableSlaConformance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2NullableSlaConformance() *ManaV2NullableSlaConformance {
	this := ManaV2NullableSlaConformance{}
	return &this
}

// NewManaV2NullableSlaConformanceWithDefaults instantiates a new ManaV2NullableSlaConformance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2NullableSlaConformanceWithDefaults() *ManaV2NullableSlaConformance {
	this := ManaV2NullableSlaConformance{}
	return &this
}

// GetSlaConformance returns the SlaConformance field value if set, zero value otherwise.
func (o *ManaV2NullableSlaConformance) GetSlaConformance() ManaV2SlaConformance {
	if o == nil || IsNil(o.SlaConformance) {
		var ret ManaV2SlaConformance
		return ret
	}
	return *o.SlaConformance
}

// GetSlaConformanceOk returns a tuple with the SlaConformance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2NullableSlaConformance) GetSlaConformanceOk() (*ManaV2SlaConformance, bool) {
	if o == nil || IsNil(o.SlaConformance) {
		return nil, false
	}
	return o.SlaConformance, true
}

// HasSlaConformance returns a boolean if a field has been set.
func (o *ManaV2NullableSlaConformance) HasSlaConformance() bool {
	if o != nil && !IsNil(o.SlaConformance) {
		return true
	}

	return false
}

// SetSlaConformance gets a reference to the given ManaV2SlaConformance and assigns it to the SlaConformance field.
func (o *ManaV2NullableSlaConformance) SetSlaConformance(v ManaV2SlaConformance) {
	o.SlaConformance = &v
}

func (o ManaV2NullableSlaConformance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2NullableSlaConformance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SlaConformance) {
		toSerialize["slaConformance"] = o.SlaConformance
	}
	return toSerialize, nil
}

type NullableManaV2NullableSlaConformance struct {
	value *ManaV2NullableSlaConformance
	isSet bool
}

func (v NullableManaV2NullableSlaConformance) Get() *ManaV2NullableSlaConformance {
	return v.value
}

func (v *NullableManaV2NullableSlaConformance) Set(val *ManaV2NullableSlaConformance) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2NullableSlaConformance) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2NullableSlaConformance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2NullableSlaConformance(val *ManaV2NullableSlaConformance) *NullableManaV2NullableSlaConformance {
	return &NullableManaV2NullableSlaConformance{value: val, isSet: true}
}

func (v NullableManaV2NullableSlaConformance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2NullableSlaConformance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


