/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2NullableSakConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2NullableSakConfiguration{}

// ManaV2NullableSakConfiguration struct for ManaV2NullableSakConfiguration
type ManaV2NullableSakConfiguration struct {
	Sak *ManaV2SakConfiguration `json:"sak,omitempty"`
}

// NewManaV2NullableSakConfiguration instantiates a new ManaV2NullableSakConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2NullableSakConfiguration() *ManaV2NullableSakConfiguration {
	this := ManaV2NullableSakConfiguration{}
	return &this
}

// NewManaV2NullableSakConfigurationWithDefaults instantiates a new ManaV2NullableSakConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2NullableSakConfigurationWithDefaults() *ManaV2NullableSakConfiguration {
	this := ManaV2NullableSakConfiguration{}
	return &this
}

// GetSak returns the Sak field value if set, zero value otherwise.
func (o *ManaV2NullableSakConfiguration) GetSak() ManaV2SakConfiguration {
	if o == nil || IsNil(o.Sak) {
		var ret ManaV2SakConfiguration
		return ret
	}
	return *o.Sak
}

// GetSakOk returns a tuple with the Sak field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2NullableSakConfiguration) GetSakOk() (*ManaV2SakConfiguration, bool) {
	if o == nil || IsNil(o.Sak) {
		return nil, false
	}
	return o.Sak, true
}

// HasSak returns a boolean if a field has been set.
func (o *ManaV2NullableSakConfiguration) HasSak() bool {
	if o != nil && !IsNil(o.Sak) {
		return true
	}

	return false
}

// SetSak gets a reference to the given ManaV2SakConfiguration and assigns it to the Sak field.
func (o *ManaV2NullableSakConfiguration) SetSak(v ManaV2SakConfiguration) {
	o.Sak = &v
}

func (o ManaV2NullableSakConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2NullableSakConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sak) {
		toSerialize["sak"] = o.Sak
	}
	return toSerialize, nil
}

type NullableManaV2NullableSakConfiguration struct {
	value *ManaV2NullableSakConfiguration
	isSet bool
}

func (v NullableManaV2NullableSakConfiguration) Get() *ManaV2NullableSakConfiguration {
	return v.value
}

func (v *NullableManaV2NullableSakConfiguration) Set(val *ManaV2NullableSakConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2NullableSakConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2NullableSakConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2NullableSakConfiguration(val *ManaV2NullableSakConfiguration) *NullableManaV2NullableSakConfiguration {
	return &NullableManaV2NullableSakConfiguration{value: val, isSet: true}
}

func (v NullableManaV2NullableSakConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2NullableSakConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


