/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceUpdateDnsproxyEntryPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceUpdateDnsproxyEntryPostRequest{}

// V2AssuranceUpdateDnsproxyEntryPostRequest struct for V2AssuranceUpdateDnsproxyEntryPostRequest
type V2AssuranceUpdateDnsproxyEntryPostRequest struct {
	DnsproxyEntry *AssuranceDnsProxyEntry `json:"dnsproxyEntry,omitempty"`
}

// NewV2AssuranceUpdateDnsproxyEntryPostRequest instantiates a new V2AssuranceUpdateDnsproxyEntryPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceUpdateDnsproxyEntryPostRequest() *V2AssuranceUpdateDnsproxyEntryPostRequest {
	this := V2AssuranceUpdateDnsproxyEntryPostRequest{}
	return &this
}

// NewV2AssuranceUpdateDnsproxyEntryPostRequestWithDefaults instantiates a new V2AssuranceUpdateDnsproxyEntryPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceUpdateDnsproxyEntryPostRequestWithDefaults() *V2AssuranceUpdateDnsproxyEntryPostRequest {
	this := V2AssuranceUpdateDnsproxyEntryPostRequest{}
	return &this
}

// GetDnsproxyEntry returns the DnsproxyEntry field value if set, zero value otherwise.
func (o *V2AssuranceUpdateDnsproxyEntryPostRequest) GetDnsproxyEntry() AssuranceDnsProxyEntry {
	if o == nil || IsNil(o.DnsproxyEntry) {
		var ret AssuranceDnsProxyEntry
		return ret
	}
	return *o.DnsproxyEntry
}

// GetDnsproxyEntryOk returns a tuple with the DnsproxyEntry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceUpdateDnsproxyEntryPostRequest) GetDnsproxyEntryOk() (*AssuranceDnsProxyEntry, bool) {
	if o == nil || IsNil(o.DnsproxyEntry) {
		return nil, false
	}
	return o.DnsproxyEntry, true
}

// HasDnsproxyEntry returns a boolean if a field has been set.
func (o *V2AssuranceUpdateDnsproxyEntryPostRequest) HasDnsproxyEntry() bool {
	if o != nil && !IsNil(o.DnsproxyEntry) {
		return true
	}

	return false
}

// SetDnsproxyEntry gets a reference to the given AssuranceDnsProxyEntry and assigns it to the DnsproxyEntry field.
func (o *V2AssuranceUpdateDnsproxyEntryPostRequest) SetDnsproxyEntry(v AssuranceDnsProxyEntry) {
	o.DnsproxyEntry = &v
}

func (o V2AssuranceUpdateDnsproxyEntryPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceUpdateDnsproxyEntryPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DnsproxyEntry) {
		toSerialize["dnsproxyEntry"] = o.DnsproxyEntry
	}
	return toSerialize, nil
}

type NullableV2AssuranceUpdateDnsproxyEntryPostRequest struct {
	value *V2AssuranceUpdateDnsproxyEntryPostRequest
	isSet bool
}

func (v NullableV2AssuranceUpdateDnsproxyEntryPostRequest) Get() *V2AssuranceUpdateDnsproxyEntryPostRequest {
	return v.value
}

func (v *NullableV2AssuranceUpdateDnsproxyEntryPostRequest) Set(val *V2AssuranceUpdateDnsproxyEntryPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceUpdateDnsproxyEntryPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceUpdateDnsproxyEntryPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceUpdateDnsproxyEntryPostRequest(val *V2AssuranceUpdateDnsproxyEntryPostRequest) *NullableV2AssuranceUpdateDnsproxyEntryPostRequest {
	return &NullableV2AssuranceUpdateDnsproxyEntryPostRequest{value: val, isSet: true}
}

func (v NullableV2AssuranceUpdateDnsproxyEntryPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceUpdateDnsproxyEntryPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


